name: neom_auth
description: Authentication for Open Neom.
version: 1.2.0
homepage: https://github.com/Open-Neom/neom_auth
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Open-Neom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Open-Neom/neom_commons.git

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
  #  firebase_auth: ^6.0.1

  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
